package main

import (
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/beeper/desktop-api-go/resources"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSanitizeFilename(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"simple", "Project Team", "project-team"},
		{"mixed punctuation", "Beeper (Matrix)", "beeper-matrix"},
		{"emoji and symbols", "🔥 Launch!", "launch"},
		{"repeated separators", "Name__With--Various   Spaces", "name-with-various-spaces"},
		{"empty result fallback", "???", "chat"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, sanitizeFilename(tt.input))
		})
	}
}

func TestTruncateString(t *testing.T) {
	assert.Equal(t, "short", truncateString("short", 10))
	assert.Equal(t, "short", truncateString("short", 5))
	assert.Equal(t, "hell...", truncateString("hello world", 7))
}

func TestFormatFileSize(t *testing.T) {
	assert.Equal(t, "512 B", formatFileSize(512))
	assert.Equal(t, "2.0 KB", formatFileSize(2048))
	assert.Equal(t, "1.5 KB", formatFileSize(1536))
	assert.Equal(t, "5.0 MB", formatFileSize(5*1024*1024))
}

func TestGetArchiveFilename(t *testing.T) {
	nowDate := time.Now().Format("2006-01-02")

	chat := resources.Chat{
		Network: "Matrix",
		Title:   "Project Updates 🚀",
	}

	filename := getArchiveFilename(chat)
	require.True(t, strings.HasSuffix(filename, ".md"))

	parts := strings.SplitN(strings.TrimSuffix(filename, ".md"), "_", 3)
	require.Len(t, parts, 3)
	assert.Equal(t, nowDate, parts[0])
	assert.Equal(t, "matrix", parts[1])
	assert.Equal(t, "project-updates", parts[2])

	longTitle := strings.Repeat("A", 60)
	longFilename := getArchiveFilename(resources.Chat{Network: "iMessage", Title: longTitle})
	longParts := strings.SplitN(strings.TrimSuffix(longFilename, ".md"), "_", 3)
	require.Len(t, longParts, 3)
	assert.Equal(t, nowDate, longParts[0])
	assert.Equal(t, "imessage", longParts[1])
	assert.LessOrEqual(t, len(longParts[2]), 50)
}

func TestGenerateMarkdown(t *testing.T) {
	lastActivity := "2025-10-07T12:34:56Z"
	chat := resources.Chat{
		ID:        "!updates:beeper.local",
		AccountID: "acc_123",
		Network:   "Beeper (Matrix)",
		Title:     "Product Updates",
		Participants: resources.ChatParticipants{
			Total: 2,
			Items: []resources.User{
				{
					ID:       "@alice:beeper.com",
					FullName: ptr("Alice"),
				},
				{
					ID: "@bob:beeper.com",
				},
			},
		},
		LastActivity: &lastActivity,
	}

	ts1 := time.Date(2025, 10, 7, 12, 0, 0, 0, time.UTC)
	ts2 := ts1.Add(5 * time.Minute)

	messages := []resources.Message{
		{
			MessageID:  "msg_1",
			Timestamp:  ts1,
			SenderName: ptr("Alice"),
			Text:       ptr("Hello\nWorld"),
			Attachments: []resources.Attachment{
				{
					Type:     "img",
					FileName: ptr("photo.png"),
					FileSize: ptr(int64(2048)),
					SrcURL:   ptr("https://example.com/photo.png"),
				},
			},
			Reactions: []resources.Reaction{{ReactionKey: "👍"}},
		},
		{
			MessageID:  "msg_2",
			Timestamp:  ts2,
			SenderName: ptr("Bob"),
		},
	}

	markdown := generateMarkdown(chat, messages)

	assert.Contains(t, markdown, "# Product Updates")
	assert.Contains(t, markdown, "**Network:** Beeper (Matrix)")
	assert.Contains(t, markdown, "**Chat ID:** `!updates:beeper.local`")
	assert.Contains(t, markdown, "## Participants")
	assert.Contains(t, markdown, "1. **Alice** (`@alice:beeper.com`)")
	assert.Contains(t, markdown, "2. **Unknown** (`@bob:beeper.com`)")

	expectedDate := fmt.Sprintf("### 📅 %s", ts1.Format("Monday, January 2, 2006"))
	assert.Contains(t, markdown, expectedDate)
	assert.Contains(t, markdown, "#### Message #1")
	assert.Contains(t, markdown, "> Hello\n> World")
	assert.Contains(t, markdown, "- Attachment 1: `photo.png` (img) - 2.0 KB")
	assert.Contains(t, markdown, "  - URL: https://example.com/photo.png")
	assert.Contains(t, markdown, "**Reactions:** 👍")
	assert.Contains(t, markdown, "> *[No text content]*")
	assert.Contains(t, markdown, "## Archive Information")
	assert.Contains(t, markdown, "*Generated by Beeper Chat Archive Tool*")
}

func ptr[T any](v T) *T {
	return &v
}
